### ISSUE TITLE
CSS will not be purged

### ISSUE THREAD

**Issue by matsp** [praveenjuge/hugo-tailwind#1]
Running `NODE_ENV=production hugo` will lead to a huge main.css.

**Comment by praveenjuge** [comment]
Hey, are you sure? I'm getting the expected small output file size. 

<img width="976" alt="Screenshot 2021-03-05 at 7 50 11 PM" src="https://user-images.githubusercontent.com/13696888/110127882-274c5580-7dec-11eb-92b8-408211a3466a.png">

**Comment by matsp** [comment]
When I reference the tailwind config with an absolute path in the postcss config it works. Looks like that postcss is running in a different context than the tailwind config on my machine.

**Comment by matsp** [comment]
This setup with tailwind & postcss only works if you are not seperating the site and theme.
