### ISSUE TITLE
Pinning PostCSS alongside PostCSS-CLI?

### ISSUE THREAD

**Issue by spookyuser** [praveenjuge/hugo-tailwind#2]
Hi, first of all thank you for the tutorial, it works perfectly as is and is so far the simplest and quickest way I've found to setup tailwind w/ Hugo. Should actually be a page in the official hugo docs IMO. 

Just wondering why you don't opt to install PostCSS with the PostCSS-CLI? Are there some incompatibilities if you do it this way?

**Comment by praveenjuge** [comment]
Hey, thanks!

I didn't add `postcss` cause I had installed it globally. But yeah it's better to install `postcss` with `postcss-cli`.

I will update the code to reflect that 👍
